apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders
  template:
    metadata:
      labels:
        app: orders
    spec:
      containers:
        - name: orders
          image: 03004968719/ms-orders # this image is only built and not deployed
          env:
            - name: MONGO_URI
              value: 'mongodb://orders-mongo-srv:27017/orders'
              #! we first need to have mongo-depl.yaml to make this work, its own db
              # in a k8s env, it is not an issue to hard coat this mongo uri because to access this,
              # someone would have to enter into the k8s cluster with my email account
              # but i can still use it as a secret
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID
              value: 'ticketing'
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name # we will get its own pod name - which is always unique
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---
# service config
apiVersion: v1
kind: Service
metadata:
  name: orders-service
spec:
  # default type is cluster-ip-service
  selector:
    app: orders
  ports:
    - name: orders
      protocol: TCP
      port: 3000
      targetPort: 3000
