apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: auth-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi # number could be anything e.g 100Gi

# spec section is requirement for the storage by k8s to local hard disk
# but in production environment, we have to define which service we wanna use to get cloud storage
# but that service will automatically be configured by the cloud provider where we will host our app

# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: auth-mongo-pv
#   labels:
#     type: local
# spec:
#   storageClassName: manual
#   capacity:
#     storage: 1Gi
#   accessModes:
#     - ReadWriteOnce
#   hostPath:
#     path: '/mnt/mongo_data'
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: auth-mongo-pv-claim
# spec:
#   storageClassName: manual
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 1Gi
# ---
