apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-upload-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: image-upload
  template:
    metadata:
      labels:
        app: image-upload
    spec:
      containers:
        - name: image-upload
          image: 03004968719/ms-image-upload # this image is only built and not deployed
          env:
            - name: MONGO_URI
              value: 'mongodb://image-upload-mongo-srv:27017/image-upload'
              #! we first need to have mongo-depl.yaml to make this work, its own db
              # in a k8s env, it is not an issue to hard coat this mongo uri because to access this,
              # someone would have to enter into the k8s cluster with my email account
              # but i can still use it as a secret
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID
              value: ticketing
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name # we will get its own pod name - which is always unique
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---
# service config
apiVersion: v1
kind: Service
metadata:
  name: image-upload-service
spec:
  # default type is cluster-ip-service
  selector:
    app: image-upload
  ports:
    - name: image-upload
      protocol: TCP
      port: 3000
      targetPort: 3000
