apiVersion: apps/v1
kind: Deployment
metadata:
  name: tickets-mongo-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tickets-mongo
  template:
    metadata:
      labels:
        app: tickets-mongo
    spec:
      volumes:
        - name: tickets-storage
          persistentVolumeClaim:
            claimName: tickets-pvc
      containers:
        - name: tickets-mongo
          image: mongo
          volumeMounts:
            - name: tickets-storage
              mountPath: /data/db-tickets
---
apiVersion: v1
kind: Service
metadata:
  name: tickets-mongo-srv
spec:
  selector:
    app: tickets-mongo
  ports:
    - name: tickets-db
      protocol: TCP
      port: 27017 # default port for mongodb
      targetPort: 27017
